use_frameworks!

platform :ios, '10.0'

target 'LCYAfnetworking_Example' do
  pod 'LCYAfnetworking', :path => '../'

  target 'LCYAfnetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
